server:
  tomcat:
    remoteip:
      protocol-header: x-forwarded-proto
      remote-ip-header: x-forwarded-for
    uri-encoding: UTF-8
    threads:
      max: 200
  error:
    whitelabel:
      enabled: false
    include-exception: false
    include-stacktrace: never
  servlet:
    encoding:
      enabled: true
      charset: UTF-8
      force: true
  forward-headers-strategy: native
  shutdown: graceful

spring:
  messages:
    basename: i18n/messages
    encoding: UTF-8
    fallback-to-system-locale: false
    use-code-as-default-message: true
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  mvc:
    favicon:
      enabled: false
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username:
    password:
    hikari:
      minimum-idle: 5
      maximum-pool-size: 5
      connection-timeout: 5000
      validation-timeout: 20000
      leak-detection-threshold: 10000
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
        useSSL: false
        useUnicode: yes
        characterEncoding: utf-8
        autoReconnect: true
        allowPublicKeyRetrieval: true
        serverTimezone: Asia/Seoul
        verifyServerCertificate: false
        requireSSL: false
  jpa:
    open-in-view: false
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  lifecycle:
    timeout-per-shutdown-phase: 30s

# swagger (springdoc)
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    csrf:
      enabled: false
    display-request-duration: true
    tags-sorter: alpha
    operations-sorter: alpha

# actuator
management:
  endpoint:
    health:
      show-details: never
    info:
      enabled: true
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include:
          - health

logging:
  level:
    root: info
    my:
      springcloud: error
    org:
      apache:
        http: error
      springframework:
        orm:
          jpa: error
        transaction: error
    jdbc:
      sqlonly: off
      sqltiming: off
      audit: off
      resultset: off
      resultsettable: off
      connection: off

# openfeign
feign:
  client:
    config:
      default:
        connectTimeout: 6000
        readTimeout: 6000
        loggerLevel: BASIC
  okhttp:
    enabled: true

# RestTemplate, HttpURLConnection 등의 타임아웃
http:
  connection-timeout: 6000
  read-timeout: 6000

my-springcloud:
  springdoc:
    component:
      security:
        schema:
          api:
            key:
  services:
    uri-root:
      account: http://localhost:9010

proxy:
  host: www.proxy.com
  port: 3128
  target:
    - 10.10.10.1
