server:
  port: ${PORT:9010}

spring:
#   config:
#    use-legacy-processing: true

logging:
  level:
    my:
      springcloud: info

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}
