server:
  port: ${PORT:9020}

spring:
  application:
    name: account-service

logging:
  level:
    my:
      springcloud: info

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}
