server:
  port: ${PORT:9010}

spring:
  application:
    name: account-service-local

logging:
  level:
    my:
      springcloud: info

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}
