spring:
  kafka:
    bootstrap-servers: ${KAFKA_ADDR:ENC(ov8AcsV7gmIVJ1CkIMJa7Xn2FLsSkcBcmsWbRJMTajqOxr/x9p0y5oguSXuIrbLorWFVRWOLqEecn030CLvogw==)}
  zipkin:
    base-url: ${ZIPKIN_SERVER:ENC(IsF5k0yzYVKtEOflSTfLDtJccNbddhaBVJcYByPEu0mYZq7bqL3xjCbHvs9MWvZSERgkVH/DukxjRek+cVo9Bw==)}

# spring
spring:
  # datasource
  datasource:
    url: jdbc:log4jdbc:mysql://146.56.160.235:3306/account
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    username: account
    password: "!@#Account123"

# logging
logging:
  file:
    name: account-service
    path: .log
  level:
    jdbc:
      sqltiming: debug
      resultsettable: debug
      connection: debug

# openfeign
feign:
  client:
    config:
      default:
        loggerLevel: FULL
