
spring:
  kafka:
    bootstrap-servers: ${KAFKA_ADDR:ENC(lOeSRAOmMa1i2ZXZPJqSnBUsUjA78soFIIoMgGVvQfJAVpFAVaYYwQEsdYgvO94pBJ3jjvQSsjB/YNdFXswJZw==)}
  zipkin:
    base-url: ${ZIPKIN_SERVER:ENC(wAMXx0ZP1BPWh2960oTkC1quQGOPRS/nnMv3dp0FoODL3K7AnojnSxzgkWiJlUkL3mhgXS09M5VlNgcTrJPFSQ==)}
