spring:
  kafka:
    bootstrap-servers: ${KAFKA_ADDR:ENC(lOeSRAOmMa1i2ZXZPJqSnBUsUjA78soFIIoMgGVvQfJAVpFAVaYYwQEsdYgvO94pBJ3jjvQSsjB/YNdFXswJZw==)}
  zipkin:
    base-url: ${ZIPKIN_SERVER:ENC(wAMXx0ZP1BPWh2960oTkC1quQGOPRS/nnMv3dp0FoODL3K7AnojnSxzgkWiJlUkL3mhgXS09M5VlNgcTrJPFSQ==)}
  # datasource
  datasource:
    url: jdbc:log4jdbc:mysql://146.56.160.235:3306/account
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    username: account
    password: "!@#Account123"
    hikari:
      minimum-idle: 10
      maximum-pool-size: 10
