server:
  port: ${PORT:8282}

spring:
  application:
    name: account-service

logging:
  level:
    my:
      springcloud: debug

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}
