server:
  port: ${PORT:9010}

spring:
  application:
    name: account-service
  cloud:
    bus:
      id: ${spring.application.name}:${spring.profiles.active}:${random.uuid}
      enabled: true
      refresh:
        enabled: true
      env:
        enabled: true

logging:
  file:
    name: ${spring.application.name}
    path: .log
  level:
    my:
      springcloud: debug
    jdbc:
      sqltiming: debug
      resultsettable: debug
      connection: debug

feign:
  client:
    config:
      default:
        loggerLevel: FULL
