spring:
  kafka:
    bootstrap-servers: ${KAFKA_ADDR:ENC(lOeSRAOmMa1i2ZXZPJqSnBUsUjA78soFIIoMgGVvQfJAVpFAVaYYwQEsdYgvO94pBJ3jjvQSsjB/YNdFXswJZw==)}
  zipkin:
    base-url: ${ZIPKIN_SERVER:ENC(wAMXx0ZP1BPWh2960oTkC1quQGOPRS/nnMv3dp0FoODL3K7AnojnSxzgkWiJlUkL3mhgXS09M5VlNgcTrJPFSQ==)}
  datasource:
    url: ENC(OB+hhJxo1pIPnZR83kZA29IJuh8PfVdAaWVnth+ceVnMu8W5DJowEF5kG5n5rwYzbdP47x2sTpOfGuyL3Js0UPn23O1KhzT21M/Lo+8ikqUNtlFqTiAR/2WMYDHzDelp)
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    username: ENC(Zm0Vw1mYW2UgGhFiNwx7jlV5p2oPyou842aBsIpoNrmU2M35DMeuhqnlIDf23evB)
    password: ENC(Uf7qBLelaqxzMATwiKO0/PZS88mxIiW1bBdiZVWmX4KsZTq0Pl41Z01DWJswRWrL)
    hikari:
      minimum-idle: 10
      maximum-pool-size: 10

file:
  upload:
    root-path: C:\projects\uploads
