# spring
spring:
  kafka:
    bootstrap-servers: ${KAFKA_ADDR:ENC(lOeSRAOmMa1i2ZXZPJqSnBUsUjA78soFIIoMgGVvQfJAVpFAVaYYwQEsdYgvO94pBJ3jjvQSsjB/YNdFXswJZw==)}
  zipkin:
    base-url: ${ZIPKIN_SERVER:ENC(wAMXx0ZP1BPWh2960oTkC1quQGOPRS/nnMv3dp0FoODL3K7AnojnSxzgkWiJlUkL3mhgXS09M5VlNgcTrJPFSQ==)}
  # datasource
  datasource:
    url: jdbc:log4jdbc:mysql://146.56.160.235:3306/account
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    username: account
    password: "!@#Account123"
    hikari:
      minimum-idle: 10
      maximum-pool-size: 10

# logging
logging:
  file:
    name: account-service
    path: .log
  level:
    jdbc:
      sqltiming: debug
      resultsettable: debug
      connection: debug

# openfeign
feign:
  client:
    config:
      default:
        loggerLevel: FULL

# services root uri
my-springcloud:
  services:
    uri-root:
      account: http://localhost:9010
