server:
  port: ${PORT:9010}

spring:
  application:
    name: account-service
  sleuth:
    sampler:
      probability: 1.0
  cloud:
    bus:
      id: ${spring.application.name}:${spring.profiles.active}:${random.uuid}
      enabled: true
      refresh:
        enabled: true
      env:
        enabled: true

logging:
  level:
    my:
      springcloud: debug

eureka:
  client:
    registry-fetch-interval-seconds: 10
    disable-delta: true
    lease-renewal-interval-in-seconds: 3
    lease-expiration-duration-in-seconds: 10
    serviceUrl:
      defaultZone: ${EUREKA_SERVER:http://localhost:8761}/eureka/
  instance:
    prefer-ip-address: true

management:
  endpoint:
    info:
      enabled: true
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include:
          - busrefresh
          - busenv
          - health
