server:
  port: ${PORT:8282}

spring:
  application:
    name: gateway-server
  config:
    activate:
      on-profile: local
#    use-legacy-processing: true
  cloud:
    gateway:
      routes:
        - id: sample-api
          # 유레카없이 사용할 경우, uri: http://localhost:9010/
          uri: lb://sample-api
          predicates:
            - Path=/api/sample/**
            # - RewritePath=/api/sample/(?<path>.*),/api/$\{path}
