server:
  port: ${PORT:8282}

spring:
  application:
    name: gateway-server
  sleuth:
    sampler:
      probability: 1.0
  zipkin:
    base-url: ${ZIPKIN_SERVER:http://localhost:9411}
  cloud:
    # https://pamesh12.github.io/spring-cloud/spring-cloud-bus.html
    # https://medium.com/@athulravindran/spring-cloud-config-server-auto-refresh-using-apache-kafka-in-kubernetes-86e3c427926e
    bus:
      id: ${spring.application.name}:${spring.profiles.active}:${random.uuid}
      enabled: true
      refresh:
        enabled: true
      env:
        enabled: true
    gateway:
      routes:
        - id: sample-service
          # 유레카없이 사용할 경우, uri: http://localhost:9010/
          uri: lb://sample-service
          predicates:
            - Path=/api/sample/**
            # - RewritePath=/api/sample/(?<path>.*),/api/$\{path}
        - id: account-service
          uri: lb://account-service
          predicates:
            - Path=/api/account/**

logging:
  level:
    my:
      springcloud: debug

eureka:
  client:
    registry-fetch-interval-seconds: 10
    disable-delta: true
    lease-renewal-interval-in-seconds: 3
    lease-expiration-duration-in-seconds: 10
    serviceUrl:
      defaultZone: ${EUREKA_SERVER:http://localhost:8761}/eureka/
  instance:
    prefer-ip-address: true

management:
  endpoint:
    info:
      enabled: true
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        # curl -X POST "http://localhost:8888/actuator/busrefresh", @RefreshScope가 있는 빈의 모든 prop 리프레쉬
        include:
          - busrefresh
          - busenv
          - health
