server:
  port: ${PORT:8282}

spring:
  application:
    name: gateway-server
  cloud:
    gateway:
      routes:
        - id: sample-service
          # 유레카없이 사용할 경우, uri: http://localhost:9010/
          uri: lb://sample-service
          predicates:
            - Path=/api/sample/**
            # - RewritePath=/api/sample/(?<path>.*),/api/$\{path}
        - id: account-service
          uri: lb://account-service
          predicates:
            - Path=/api/account/**
    loadbalancer:
      cache:
        enabled: false

logging:
  level:
    my:
      springcloud: debug
