server:
  port: ${PORT:8282}

spring:
  application:
    name: gateway-server
  cloud:
    # https://pamesh12.github.io/spring-cloud/spring-cloud-bus.html
    # https://medium.com/@athulravindran/spring-cloud-config-server-auto-refresh-using-apache-kafka-in-kubernetes-86e3c427926e
    bus:
      id: ${spring.application.name}:${spring.profiles.active}:${random.uuid}
      enabled: true
      refresh:
        enabled: true
      env:
        enabled: true
    gateway:
      routes:
        - id: sample-service
          # 유레카없이 사용할 경우, uri: http://localhost:9010/
          uri: lb://sample-service
          predicates:
            - Path=/api/sample/**
            # - RewritePath=/api/sample/(?<path>.*),/api/$\{path}
        - id: account-service
          uri: lb://account-service
          predicates:
            - Path=/api/account/**
    loadbalancer:
      cache:
        enabled: false

logging:
  level:
    my:
      springcloud: debug
